OpenTreeMap/otm-ios

- OpenTreeMap/src/OTM/OTMEnvironment.m
The application was crashing attempting to convert saved numeric UDF values from numbers to strings, which occurs when showing the edit form with an integer UDF that has a saved value.
Checking the data type of the UDF and creating a numeric formatter for the field when it has the ``int`` or ``float`` type activates the existing numeric field handling, fixing the issue.
The species field has a data type ``int`` (the database id of the selected species) but has highly customized field handling. I exclude it by name to prevent potential negative side effects of having ``fmt`` be non-nil on the species field object.
Connects to #224
> Allow editing and saving numeric UDFs

- OpenTreeMap/src/OTM/Controllers/OTMInstanceSelectTableViewController.m
The button at the bottom of the initial instance select table view segues to a filterable list of public tree maps, not a list of "All" tree maps, as the previous button label suggested.
Connects to #241
> Correct "Search All..." to "Search Public..."

- OpenTreeMap/src/OTM/Controllers/OTMMapViewController.m
- OpenTreeMap/src/OTM/OTMTreeDictionaryHelper.m
CLLocationCoordinate2D is a struct with latitude and longitude stored as doubles. When saving coordinates into a dictionary via NSNumber the conversion from double to float was causing a loss of numeric precision and, therefore, a loss of accuracy in setting the location of a plot.
The inaccuracy was most pronounced when coordinates have three digits to the left of the decimal point.
```
{
plot =     {
"address_city" = Reno;
"address_street" = "400\U2013498 E 6th St";
"address_zip" = 89512;
geom =         {
srid = 4326;
x = "-119.8077";
y = "39.53378";
};
};
tree =     {
};
}
```
```
{
plot =     {
"address_city" = Reno;
"address_street" = "400\U2013498 E 6th St";
"address_zip" = 89512;
geom =         {
srid = 4326;
x = "-119.807749073744";
y = "39.53377992317881";
};
};
tree =     {
};
} …
```
> Serialize coordinates as double to keep precision

- OpenTreeMap/OpenTreeMap.xcodeproj/project.pbxproj
- lib/asi/ASI.xcodeproj/project.pbxproj
Building 64-bit binaries is now required when submitting an app to the App Store. Using the default value of ARCHS_STANDARD builds armv7 and arm64.
The project should build without errors.
Connects to #231
> Switch architectures to ARCHS_STANDARD

- OpenTreeMap/src/OTM/Controllers/OTMProfileViewController.m
The user edits endpoint is broken in the latest version of the API, and the existing code to display edits does not display them properly. Until both of these issues are fixed I am disabling the loading of recent edits.
When viewing the profile of a user who has edited the map
- No audit details are displayed at the bottom of the profile
- Pulling up beyond the bottom of the profile content does not cause a "pull to refresh" view to appear. 
- No requests are made to the broken edits API.
---
Connects to #252
> Disable requesting user edits

- OpenTreeMap/src/OTM/Controllers/OTMInstanceSelectTableViewController.h
- OpenTreeMap/src/OTM/Controllers/OTMInstanceSelectTableViewController.m
- OpenTreeMap/src/OTM/OTMAPI.h
- OpenTreeMap/src/OTM/OTMAPI.m
- OpenTreeMap/src/OTM/OTMLocationManager.h
- OpenTreeMap/src/OTM/OTMLocationManager.m
- Add a spinner to the right of the navigation bar whenever the app is waiting for the location manager to find the user's position or the app is waiting for a network response.
- Use a less precise accuracy requirement when trying to find the user's location in order to get a list of instances. 3000m is good enough given that our default instance radius is 5000m.
- Request the instances a user is a member of before attempting to find a nearby instance. Most users will only contribute to a single map and this ensures that map is available for selection as quickly as possible.
A spinner should always been shown when a location request or instance fetch request is in progress. 
You can use the location simulator in  the Xcode debugger pane to simulate a location fix both before and after …
> Improve instance loading workflow

- OpenTreeMap/src/OTM/Cells/OTMChoicesDetailCellRenderer.h
- OpenTreeMap/src/OTM/Cells/OTMChoicesDetailCellRenderer.m
- OpenTreeMap/src/OTM/Cells/OTMDetailCellRenderer.m
- OpenTreeMap/src/OTM/Cells/OTMUdfCollectionCell.h
- OpenTreeMap/src/OTM/Cells/OTMUdfCollectionCell.m
- OpenTreeMap/src/OTM/OTMEnvironment.m
Editing single choice and multichoice fields have a similar workflow so, by adding a new `isMulti` property, the existing `OTMChoicesDetailCellRenderer` can conditionally handle both types of fields.
When stewardship support was added, the `OTMDetailCellRenderer` base class used `isKindOfClass [NSArray class]` to detect a collection UDF field. Multichoice fields are also stored as arrays, requiring that we refactor this logic.
The visible difference between the single select and multiselect mode is subtle, so I added a header to the table view with and instructive message.
The `stringForValue:` method is repeated in both `OTMChoicesDetailCellRenderer` and `OTMEditChoicesDetailCellRenderer` but it is so simple that trying to DRY it out would be more complicated.
- Create an instance with a …
> Support multichoice fields

- OpenTreeMap/src/OTM/Controllers/OTMFilterListViewController.h
- OpenTreeMap/src/OTM/Controllers/OTMFilterListViewController.m
For each "toggle" filter:
* Right-justify toggle
* Use remaining space for label
* Wrap label to multiple lines if necessary
* Center toggle vertically with respect to label
Also DRY out duplicated code by adding `OTMToggleFilter` as superclass of `OTMBoolFilter` and `OTMDefaultFilter`.
Connects #268
1. Go to a tree map with alerts
2. Verify that both "Missing Data" toggles and "Alert" toggles are right justified
3. Replace this code:
```objective-c
_nameLbl.text = self.name;
```
with this code:
```objective-c
_nameLbl.text = [self.name stringByAppendingString:@", followed by a whole lot more text"];
```
4. Verify that the now-long labels wrap to 3 lines, don't overlap the toggles, and that the toggles are vertically centered.
5. Verify that both the "Missing Data" and "Alert" filters …
> Fix layout of "toggle" filters

- OpenTreeMap/src/OTM/Controllers/OTMMapViewController.m
The /location/lat,lng/plots API endpoint ignores any filters that are passed along with the request:
https://github.com/OpenTreeMap/otm-core/blob/983ffcdb0a226fc9bd6ab1fc3e3f42e47ed9e5ba/opentreemap/api/plots.py#L39
The filters have been ignored since the initial creation of the OTM2 API endpoint.
https://github.com/OpenTreeMap/otm-core/commit/b25c3b9dc90f83f6e5abc67b7396bcdc7f2cefde
---
If you run the application in the simulator, apply a filter, and then tap the map, you should see in the NSLog output that the request is sent without a `q=` parameter.
The specific bug resolved by this commit can be tested for by following the reproduction steps from #278:
On the website:
1. Create a custom planting site field named "Test Field". Make it editable and filterable on mobile.
1. Add a …
> Remove filters from map tap nearby plot request

- OpenTreeMap/src/OTM/Controllers/OTMTreeDetailViewController.m
- OpenTreeMap/src/OTM/OTMEnvironment.h
- OpenTreeMap/src/OTM/OTMEnvironment.m
Connects #263
Testing:
* Make an instance whose `public` role can upload photos but nothing else
* Verify that a `public` user can upload an image
* Verify that an admin user can still create and edit trees
> In tree save/edit, post only writable fields

- OpenTreeMap/src/OTM/Controllers/OTMSplashViewController.m
Also:
* Log warning to Rollbar that we failed to load an instance
* For skinned apps (where selecting an instance is disabled), show error dialog as we did before
Connects #287
To test:
1) Open a tree map
2) Exit the app (cmd+shift+h twice and swipe up)
3) Rename the instance in super admin
4) Launch the app
You should see a warning in rollbar, and the app should show the instance switcher.
> Allow selecting instance if previous instance fails to load

- OpenTreeMap/resources/MainStoryboard_iPhone.storyboard
- OpenTreeMap/src/OTM/Controllers/OTMMapViewController.m
- OpenTreeMap/src/OTM/OTMEnvironment.h
- OpenTreeMap/src/OTM/OTMEnvironment.m
Currently the web app allows a user to add a tree if they have write permission on certain plot fields (see e.g https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/audit.py#L496), currently just `geom`.
The results are included in the initial environment dictionary, as `dict.meta_fields.can_edit_tree`. So show the "Add" button only if the user has that "meta permission".
Logic is in `viewWillAppear` so it will change if the user logs out and logs back in as a user with different permissions.
Connects #109
Connects #296
> Only show "Add" (tree) button if user has the required permissions

- OpenTreeMap/src/OTM/OTMAppDelegate.m
- OpenTreeMap/src/OTM/OTMEnvironment.h
- OpenTreeMap/src/OTM/OTMEnvironment.m
By default Rollbar logs all items as "development." Adding a new Implementation.plist key allows for staging or production builds to log events under the appropriate environment name.
---
Make sure the application runs properly without the additional `environmentName` key in `Implementation.plist`
Launch the app with different values of `environmentName` and verify that items appear in Rollbar with the correct environment.
---
Depends on https://github.com/OpenTreeMap/otm-mobile-skins/pull/76
Connects to https://github.com/OpenTreeMap/otm-ios/issues/295
> Read Rollbar environment from Implementation.plist

- OpenTreeMap/src/OTM/Cells/OTMDetailCellRenderer.h
- OpenTreeMap/src/OTM/Cells/OTMDetailCellRenderer.m
- OpenTreeMap/src/OTM/Controllers/OTMTreeDetailViewController.m
The `OTMStaticClickCellRenderer` now hangs on to its `detailcell` and the `OTMTreeDetailViewController` updates the
`detailcell`'s label directly.
Connects #281
> Update cell correctly when choosing a species for a new tree

- OpenTreeMap/OpenTreeMap.xcodeproj/project.pbxproj
Bitcode is a part of "App Thinning"
https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html
Rollbar does not support Bitcode. From https://rollbar.com/docs/notifier/rollbar-ios/
> PLCrashReporter does not yet support symbolicating apps built with
> bitcode. Until a version of PLCrashReporter is available that supports
> symbolication with bitcode enabled, you'll need to disable bitcode in
> your project for Rollbar to be able to symbolicate your crash reports.
> Disable Bitcode

- OpenTreeMap/src/OTM/OTMPreferences.h
The app was crashing with an `EXC_BAD_ACCESS` exception when the app delegate's `applicationDidEnterBackground:` method attempted to call `save` on `OTMPreferences`. Setting a breakpoint on unhandled exceptions revealed that the value of the `instance` property was invalid. It looks like this is the result of using the `assign` attribute, which should only be used on primitive types (int, BOOL, etc.).
I am not able to reproduce the exception after replacing `assign` with our app-wide convention for string properties, `nonatomic` and `strong`.
---
Follow the reproduction steps in #323.
---
Connects to #323
> Change property attributes on OTMPreferences

- OpenTreeMap/OpenTreeMap.xcodeproj/project.pbxproj
We encountered build errors after updating our CI node to OS X 10.11 and Xcode 8. Setting the provisioning style to "Manual" allows our command line CI builds to specify the desired profile without running into conflicts.
We have also removed the deprecated CODE_SIGN_RESOURCE_RULES_PATH setting which was generating warnings.
> Set the OTM target signing to manual

- OpenTreeMap/OpenTreeMap-Info.plist.template
Versions of the application built with Xcode 8 crash on iOS 10 when trying to access the camera or photo library unless we provide messages to be shown to the user.
This Apple documentation page confirms that both of these new keys are available in our target OS version, iOS 7.1+
https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html
---
Check out the `master` branch, build it with Xcode 8, and run it on a physical device with iOS 10+ installed. You should see the application crash when you attempt to add a photo from the camera or the photo library. Repeat the process on this branch and the crashes should be resolved.
--- 
Connects to #328
> Add camera and photo library usage messages

- OpenTreeMap/OpenTreeMap.xcodeproj/project.pbxproj
These paths were removed when adding CocoaPods, but we ran into linker errors when building the "Ad Hoc" configuration in CI. Restoring these search paths resolved the linker errors.
---
Connects to https://github.com/azavea/trees-team/issues/102
> Restore library search paths

- OpenTreeMap/src/OTM/Controllers/OTMTreeDetailViewController.m
- OpenTreeMap/src/OTM/OTMEnvironment.h
- OpenTreeMap/src/OTM/OTMEnvironment.m
Use `meta_perms["can_edit_tree_photo"]` (as the Android app does), which respects new-style permissions.
Testing:
1. Add a tree and verify that The "Picture" field says "Tree Picture"
1. Turn off the "Can Add Tree Photo" permission for the user's role
1. Add a tree and verify that The "Picture" field says "Picture cannot be changed"
Connects OpenTreeMap/otm-clients#334
> Use correct info to enable/disable adding tree photos

- OpenTreeMap/src/OTM/Controllers/OTMImageViewController.m
- Replace deprecated `presentModalViewController` with `presentViewController`.
- Check the `canSendMail` static method before attempting to use the
`OTMInappropriateContentMailViewController` to present a view controller. This
prevents a crash when email has not been configured on the device.
---
- Run the app in the simulator
- Create a tree with a photo
- Re-select the tree on the map page and tap the photo
- Tap report. You should see a dialog instead of crashing
- Run the app on a device with a configured email account
- Create a tree with a photo
- Re-select the tree on the map page and tap the photo
- Tap report. A draft email view should appear with the tree and photo details.
---
Connects to #312
> Update photo report email view controller usage

- OpenTreeMap/src/OTM/Controllers/OTMTreeDetailViewController.m
`readonly` is a special field that has not been implemented in the backend. Editing an empty planting site was incorrectly creating a tree because the app was sending "false" for the value of `tree.readonly`. The simplest way to handle this was to simply filter out the `readonly` field before PUTing/POSTing to the API.
---
- Log in as an user in the Administrator role for an instance.
- Add an empty plot.
- Edit the plot then tap "Done" without changing any values. Verify that a tree was not created.
---
Connects to #284
> Exclude readonly when saving tree/plot.

- OpenTreeMap/src/OTM/Controllers/OTMMapViewController.m
- OpenTreeMap/src/OTM/Controllers/OTMTreeDetailViewController.m
Previous to these changes a failure to save an image put the application into an inconsistent state. After showing an error message, the map page was still in the "add tree" mode with the movable marker appearing on the map.
These changes address that problem by calling slightly different versions the same post-save actions. We have added a separate and more helpful error message in the case when saving the photo of a new tree fails vs. when adding a photo to an existing tree fails.
We have also implemented `viewController:addedTree:` in `OTMMapViewController.m`. That method was defined in the `.h` file but the implementation was mistakenly omitted.
---
- Add an exception to the `add_photo` view to force photo uploads to fail.
```diff
diff --git a/opentreemap/api/views.py …
```
> Fix the workflow when a tree is created but photo saving fails

- OpenTreeMap/src/OTM/Cells/OTMDetailCellRenderer.h
- OpenTreeMap/src/OTM/Cells/OTMDetailCellRenderer.m
- OpenTreeMap/src/OTM/Cells/OTMDetailTableViewCell.h
- OpenTreeMap/src/OTM/Cells/OTMDetailTableViewCell.m
Before this commit setting the value of a date field to the current date required changing the date picker to some other value and then changing it back to the current date. This commit fixes that workflow by setting the date field value on focus and adding a toolbar with a "Clear" button to remove the value if it was set accidentally.
To properly clear a previously saved date value required changing the implementation of `updateDictWithValueFromCell:` to set an `NSNull` in the dictionary rather than omitting the key from the dictionary entirely.
The `updatedString` property is nil in two situations, the field was initially empty or an initially non-empty field was cleared. To remove the ambiguity I added two new properties to keep track of the initial value of the field and whether or …
> Update date field handling

- OpenTreeMap/src/OTM/Cells/OTMChoicesDetailCellRenderer.m
- OpenTreeMap/src/OTM/Cells/OTMUdfCollectionCell.m
When using the iOS "Larger Text" accessibility feature custom stewardship options and choice field options were being truncated rather than wrapping to a new line.  setting `numberOfLines` to zero and setting the row height on the parent table view to automatically increase the row height as needed resolves the issue.
Connects https://github.com/OpenTreeMap/otm-clients/issues/431 
* Create a new instance and add the tree stewardship options shown in the Demo screenshots and a custom choice field with a long option as shown in the Demo screenshots.
* Connect to the instance from the iOS app, add a tree, and verify that the choice field options and stewardship options wrap correctly.
> Support large text in stewardship items and choice field items

- OpenTreeMap/src/OTM/Controllers/OTMTreeDetailViewController.m
The species field is a special-case field and has previously been pinned to the top of the edit view along with photo field. This commit makes the species field respect the field sequence set on the management page.
Connects #365
* Create an instance called `mobile-field-order`
* Browse http://localhost:6060/mobile-field-order/management/field-configuration/, click the `Mobile` tab, and click `Edit`
* Move the `Species` field down between `Tree Height` and `Date Planted` and click `Save`
* Run the iOS app and log in with the same account used to create the `mobile-field-order` instance and switch to the `mobile-field-order` instance.
* Add a tree. Verify that the species field is shown in the correct order. 
* Add a second tree, then go back and edit the first tree. Verify that the …
> Show the species edit field in instance defined order
